//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo.SIANCentral
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.Web.Script.Serialization;
    using Newtonsoft.Json;
    //[Serializable]
    public partial class CatCuotasCrm
    {
        public int Id_Cd { get; set; }
        public int Id_rik { get; set; }
        public int Cuo_Anio { get; set; }
        public int Cuo_Mes { get; set; }
        public Nullable<double> Cuo_MontoProy { get; set; }
        public Nullable<double> Cuo_MontoCierre { get; set; }
        public Nullable<int> Cuo_NumProy { get; set; }
        public Nullable<int> Cuo_NumProyCierre { get; set; }
    }
}
