//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo.SIANCentral
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Common;
    using System.Linq;
    
    public partial class SIANCentralEntities1 : DbContext
    {
    	public SIANCentralEntities1(String nameOrConnectionString)
            : base(nameOrConnectionString)
        {
    		Setup();
        }
    
    	public SIANCentralEntities1(DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
    		Setup();
        }
    
        public SIANCentralEntities1()
            : base("name=SIANCentralEntities1")
        {
    		Setup();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    	partial void Setup();
    
        public DbSet<CatCuotasCrm> CatCuotasCrms { get; set; }
        public DbSet<CatCDI> CatCDIs { get; set; }
    }
}
