//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SIANWEB.WS_CFDICancelacion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CancelacionWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaEdoCFDIOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperaCFDIOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::SIANWEB.Properties.Settings.Default.SIANWEB_WS_CFDICancelacion_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CancelacionWSCompletedEventHandler CancelacionWSCompleted;
        
        /// <remarks/>
        public event ConsultaEdoCFDICompletedEventHandler ConsultaEdoCFDICompleted;
        
        /// <remarks/>
        public event RecuperaCFDICompletedEventHandler RecuperaCFDICompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelacionWS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CancelacionWS(string Parametros) {
            object[] results = this.Invoke("CancelacionWS", new object[] {
                        Parametros});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CancelacionWSAsync(string Parametros) {
            this.CancelacionWSAsync(Parametros, null);
        }
        
        /// <remarks/>
        public void CancelacionWSAsync(string Parametros, object userState) {
            if ((this.CancelacionWSOperationCompleted == null)) {
                this.CancelacionWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelacionWSOperationCompleted);
            }
            this.InvokeAsync("CancelacionWS", new object[] {
                        Parametros}, this.CancelacionWSOperationCompleted, userState);
        }
        
        private void OnCancelacionWSOperationCompleted(object arg) {
            if ((this.CancelacionWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelacionWSCompleted(this, new CancelacionWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaEdoCFDI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaEdoCFDI(string RFCEmisor, string RFCReceptor, string TotalCFDI, string FolioFiscal, string SD) {
            object[] results = this.Invoke("ConsultaEdoCFDI", new object[] {
                        RFCEmisor,
                        RFCReceptor,
                        TotalCFDI,
                        FolioFiscal,
                        SD});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaEdoCFDIAsync(string RFCEmisor, string RFCReceptor, string TotalCFDI, string FolioFiscal, string SD) {
            this.ConsultaEdoCFDIAsync(RFCEmisor, RFCReceptor, TotalCFDI, FolioFiscal, SD, null);
        }
        
        /// <remarks/>
        public void ConsultaEdoCFDIAsync(string RFCEmisor, string RFCReceptor, string TotalCFDI, string FolioFiscal, string SD, object userState) {
            if ((this.ConsultaEdoCFDIOperationCompleted == null)) {
                this.ConsultaEdoCFDIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaEdoCFDIOperationCompleted);
            }
            this.InvokeAsync("ConsultaEdoCFDI", new object[] {
                        RFCEmisor,
                        RFCReceptor,
                        TotalCFDI,
                        FolioFiscal,
                        SD}, this.ConsultaEdoCFDIOperationCompleted, userState);
        }
        
        private void OnConsultaEdoCFDIOperationCompleted(object arg) {
            if ((this.ConsultaEdoCFDICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaEdoCFDICompleted(this, new ConsultaEdoCFDICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecuperaCFDI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecuperaCFDI(string Parametros) {
            object[] results = this.Invoke("RecuperaCFDI", new object[] {
                        Parametros});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperaCFDIAsync(string Parametros) {
            this.RecuperaCFDIAsync(Parametros, null);
        }
        
        /// <remarks/>
        public void RecuperaCFDIAsync(string Parametros, object userState) {
            if ((this.RecuperaCFDIOperationCompleted == null)) {
                this.RecuperaCFDIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperaCFDIOperationCompleted);
            }
            this.InvokeAsync("RecuperaCFDI", new object[] {
                        Parametros}, this.RecuperaCFDIOperationCompleted, userState);
        }
        
        private void OnRecuperaCFDIOperationCompleted(object arg) {
            if ((this.RecuperaCFDICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperaCFDICompleted(this, new RecuperaCFDICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void CancelacionWSCompletedEventHandler(object sender, CancelacionWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelacionWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelacionWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ConsultaEdoCFDICompletedEventHandler(object sender, ConsultaEdoCFDICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaEdoCFDICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaEdoCFDICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void RecuperaCFDICompletedEventHandler(object sender, RecuperaCFDICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperaCFDICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperaCFDICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591