//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo_CC.CuentasCoorporativas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatACYS_SIANCENTRAL
    {
        public int Id { get; set; }
        public Nullable<int> NumClienteMac { get; set; }
        public string NombreClienteMac { get; set; }
        public string StrCondicionesClienteMac { get; set; }
        public string CalleClienteMac { get; set; }
        public string CiudadClienteMac { get; set; }
        public string ZonaPostalClienteMac { get; set; }
        public string PaisClienteMac { get; set; }
        public string EstadoClienteMac { get; set; }
        public Nullable<int> StrTipoClienteMac { get; set; }
        public Nullable<int> TerritorioClienteMac { get; set; }
        public Nullable<int> VendedorClienteMac { get; set; }
        public Nullable<int> TarifaImpClienteMac { get; set; }
        public Nullable<bool> GravableClienteMac { get; set; }
        public Nullable<bool> PagoComisionClienteMac { get; set; }
        public Nullable<bool> ActCostoGarantíaClienteMac { get; set; }
        public string RFCClienteMac { get; set; }
        public string ColoniaClienteMac { get; set; }
        public string MedioEnvioClienteMac { get; set; }
        public string ConvenioId { get; set; }
        public string ConvenioNombre { get; set; }
        public string NumeroClienteMac { get; set; }
    }
}
