//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo_CC.CuentasCoorporativas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatACYS_DirFiscales
    {
        public int Id { get; set; }
        public Nullable<int> Id_ClienteMatriz { get; set; }
        public string ClienteDirFis { get; set; }
        public string DireccionDirFis { get; set; }
        public string EstadoDirFis { get; set; }
        public string ColoniaDirFis { get; set; }
        public string CPDirFis { get; set; }
        public string MunicipioDirFis { get; set; }
        public string RFCDirFis { get; set; }
        public string EmailFacturasDirFis { get; set; }
        public string NumeroDirFis { get; set; }
    }
}
