//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo_CC.CuentasCoorporativas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatACYS_Productos_DatosGar_Fechas
    {
        public int Id { get; set; }
        public Nullable<int> Id_ACYS { get; set; }
        public Nullable<int> Id_TG { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<System.DateTime> FechaCorte { get; set; }
        public Nullable<bool> Facturado { get; set; }
    
        public virtual CatCNac_ACYS CatCNac_ACYS { get; set; }
    }
}
