//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo_CC.CuentasCoorporativas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatCNac_PermisosCamposACYS
    {
        public int Id { get; set; }
        public string NOMBRE { get; set; }
        public string Campo { get; set; }
        public string ACYS_CENTRAL { get; set; }
        public string CDIK { get; set; }
        public string obligatorio { get; set; }
        public string Cnacional { get; set; }
        public string Coordinada { get; set; }
        public string CEDIS { get; set; }
        public string Otra { get; set; }
    }
}
