//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo_CC.CuentasCoorporativas
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatCNac_Estructura
    {
        public CatCNac_Estructura()
        {
            this.CatCNac_Solicitudes = new HashSet<CatCNac_Solicitudes>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_Matriz { get; set; }
        public string NombreNodo { get; set; }
        public Nullable<int> Nivel { get; set; }
        public Nullable<int> NodoPadre { get; set; }
        public Nullable<int> Nivel_ACYS { get; set; }
        public Nullable<int> Sucursal { get; set; }
        public string NombreSucursal { get; set; }
        public Nullable<int> id_Acys { get; set; }
        public Nullable<int> Id_Cte { get; set; }
        public Nullable<int> Id_Emp { get; set; }
        public Nullable<int> Id_Cd { get; set; }
        public Nullable<int> Id_Ter { get; set; }
    
        public virtual CatCNac_ACYS CatCNac_ACYS { get; set; }
        public virtual CatCNac_Matriz CatCNac_Matriz { get; set; }
        public virtual ICollection<CatCNac_Solicitudes> CatCNac_Solicitudes { get; set; }
        public virtual CatCliente CatCliente { get; set; }
    }
}
