//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo_CC.CuentasCoorporativas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
        using System.Data.Entity.Core;
        using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sianwebmty_CCEntities : DbContext
    {
        public sianwebmty_CCEntities()
            : base("name=sianwebmty_CCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CatClienteDetGarantia> CatClienteDetGarantias { get; set; }
        public DbSet<CatTipoGarantia> CatTipoGarantias { get; set; }
        public DbSet<CatTipoVenta> CatTipoVentas { get; set; }
        public DbSet<CapAcysExt> CapAcysExts { get; set; }
        public DbSet<CapAcysDet> CapAcysDets { get; set; }
        public DbSet<CatClienteDet> CatClienteDet { get; set; }
        public DbSet<CapRemision> CapRemisions { get; set; }
        public DbSet<CapAcysDatosGarantia> CapAcysDatosGarantias { get; set; }
        public DbSet<CapNotificacionExcesoMeta> CapNotificacionExcesoMetas { get; set; }
        public DbSet<CapConfiguracionGlobal> CapConfiguracionGlobals { get; set; }
        public DbSet<CatACYS_Cliente> CatACYS_Cliente { get; set; }
        public DbSet<CatACYS_CondPago> CatACYS_CondPago { get; set; }
        public DbSet<CatACYS_DirFiscales> CatACYS_DirFiscales { get; set; }
        public DbSet<CatACYS_OtrosApoyos> CatACYS_OtrosApoyos { get; set; }
        public DbSet<CatAcys_Productos> CatAcys_Productos { get; set; }
        public DbSet<CatACYS_Productos_DatosGar> CatACYS_Productos_DatosGar { get; set; }
        public DbSet<CatACYS_Productos_DatosGar_Fechas> CatACYS_Productos_DatosGar_Fechas { get; set; }
        public DbSet<CatACYS_RecPedido> CatACYS_RecPedido { get; set; }
        public DbSet<CatACYS_ServValor> CatACYS_ServValor { get; set; }
        public DbSet<CatACYS_SIANCENTRAL> CatACYS_SIANCENTRAL { get; set; }
        public DbSet<CatACYSProductos_DatosGar> CatACYSProductos_DatosGar { get; set; }
        public DbSet<CatCNac_ACYS> CatCNac_ACYS { get; set; }
        public DbSet<CatCNac_EstatusSolicitudes> CatCNac_EstatusSolicitudes { get; set; }
        public DbSet<CatCNac_Estructura> CatCNac_Estructura { get; set; }
        public DbSet<CatCNac_Matriz> CatCNac_Matriz { get; set; }
        public DbSet<CatCNac_PermisosCamposACYS> CatCNac_PermisosCamposACYS { get; set; }
        public DbSet<CatCNac_RemisionesMov80> CatCNac_RemisionesMov80 { get; set; }
        public DbSet<CatCNac_Solicitudes> CatCNac_Solicitudes { get; set; }
        public DbSet<CatCNac_Solicitudes_DirFiscal> CatCNac_Solicitudes_DirFiscal { get; set; }
        public DbSet<CatCNac_Usuario> CatCNac_Usuario { get; set; }
        public DbSet<CatCliente> CatCliente { get; set; }
        public DbSet<CatTerritorio> CatTerritorio { get; set; }
        public DbSet<CapAcys_CNacCondPago> CapAcys_CNacCondPago { get; set; }
        public DbSet<CapACYS_CNacRecPedido> CapACYS_CNacRecPedido { get; set; }
        public DbSet<CapAcys_CNacServValor> CapAcys_CNacServValor { get; set; }
        public DbSet<Intra_CFD_CuentaNacional> Intra_CFD_CuentaNacional { get; set; }
        public DbSet<CatCNac_EmailsAutorizacion> CatCNac_EmailsAutorizacion { get; set; }
        public DbSet<CapAcy> CapAcys { get; set; }
        public DbSet<CrmOportunidades> CrmOportunidades { get; set; }
    
        public virtual ObjectResult<CatTipoGarantia> spCatTipoGarantia_Consulta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatTipoGarantia>("spCatTipoGarantia_Consulta");
        }
    
        public virtual ObjectResult<CatTipoGarantia> spCatTipoGarantia_Consulta(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatTipoGarantia>("spCatTipoGarantia_Consulta", mergeOption);
        }
    
        public virtual ObjectResult<CatClienteDetGarantia> spCatClienteDetGarantia_ConsultarPorClienteTerritorio(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Cte, Nullable<int> id_CteDet)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            var id_CteDetParameter = id_CteDet.HasValue ?
                new ObjectParameter("Id_CteDet", id_CteDet) :
                new ObjectParameter("Id_CteDet", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatClienteDetGarantia>("spCatClienteDetGarantia_ConsultarPorClienteTerritorio", id_EmpParameter, id_CdParameter, id_CteParameter, id_CteDetParameter);
        }
    
        public virtual ObjectResult<CatClienteDetGarantia> spCatClienteDetGarantia_ConsultarPorClienteTerritorio(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Cte, Nullable<int> id_CteDet, MergeOption mergeOption)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            var id_CteDetParameter = id_CteDet.HasValue ?
                new ObjectParameter("Id_CteDet", id_CteDet) :
                new ObjectParameter("Id_CteDet", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatClienteDetGarantia>("spCatClienteDetGarantia_ConsultarPorClienteTerritorio", mergeOption, id_EmpParameter, id_CdParameter, id_CteParameter, id_CteDetParameter);
        }
    
        public virtual int spCatClienteDetGarantia_Insertar(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Cte, Nullable<int> id_CteDet, Nullable<int> id_TG)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            var id_CteDetParameter = id_CteDet.HasValue ?
                new ObjectParameter("Id_CteDet", id_CteDet) :
                new ObjectParameter("Id_CteDet", typeof(int));
    
            var id_TGParameter = id_TG.HasValue ?
                new ObjectParameter("Id_TG", id_TG) :
                new ObjectParameter("Id_TG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCatClienteDetGarantia_Insertar", id_EmpParameter, id_CdParameter, id_CteParameter, id_CteDetParameter, id_TGParameter);
        }
    
        public virtual int spCatClienteDetGarantia_Eliminar(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Cte, Nullable<int> id_CteDet)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            var id_CteDetParameter = id_CteDet.HasValue ?
                new ObjectParameter("Id_CteDet", id_CteDet) :
                new ObjectParameter("Id_CteDet", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCatClienteDetGarantia_Eliminar", id_EmpParameter, id_CdParameter, id_CteParameter, id_CteDetParameter);
        }
    
        public virtual ObjectResult<CatTipoGarantia> spCatTipoGarantia_ConsultaPorNombre(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatTipoGarantia>("spCatTipoGarantia_ConsultaPorNombre", nombreParameter);
        }
    
        public virtual ObjectResult<CatTipoGarantia> spCatTipoGarantia_ConsultaPorNombre(string nombre, MergeOption mergeOption)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatTipoGarantia>("spCatTipoGarantia_ConsultaPorNombre", mergeOption, nombreParameter);
        }
    
        public virtual ObjectResult<CatTipoVenta> spCatTipoVenta_ConsultaPorNombre(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatTipoVenta>("spCatTipoVenta_ConsultaPorNombre", nombreParameter);
        }
    
        public virtual ObjectResult<CatTipoVenta> spCatTipoVenta_ConsultaPorNombre(string nombre, MergeOption mergeOption)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatTipoVenta>("spCatTipoVenta_ConsultaPorNombre", mergeOption, nombreParameter);
        }
    
        public virtual int spCapAcysExt_Insertar(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Acs, Nullable<int> id_AcsVersion, Nullable<int> id_TV, Nullable<int> id_TG)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_AcsParameter = id_Acs.HasValue ?
                new ObjectParameter("Id_Acs", id_Acs) :
                new ObjectParameter("Id_Acs", typeof(int));
    
            var id_AcsVersionParameter = id_AcsVersion.HasValue ?
                new ObjectParameter("Id_AcsVersion", id_AcsVersion) :
                new ObjectParameter("Id_AcsVersion", typeof(int));
    
            var id_TVParameter = id_TV.HasValue ?
                new ObjectParameter("Id_TV", id_TV) :
                new ObjectParameter("Id_TV", typeof(int));
    
            var id_TGParameter = id_TG.HasValue ?
                new ObjectParameter("Id_TG", id_TG) :
                new ObjectParameter("Id_TG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCapAcysExt_Insertar", id_EmpParameter, id_CdParameter, id_AcsParameter, id_AcsVersionParameter, id_TVParameter, id_TGParameter);
        }
    
        public virtual ObjectResult<CapAcysDet> spCapAcysDet_ConsultarPorProducto(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Prd, Nullable<int> id_Ter, Nullable<int> id_Cte, Nullable<int> id_Rik)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_PrdParameter = id_Prd.HasValue ?
                new ObjectParameter("Id_Prd", id_Prd) :
                new ObjectParameter("Id_Prd", typeof(int));
    
            var id_TerParameter = id_Ter.HasValue ?
                new ObjectParameter("Id_Ter", id_Ter) :
                new ObjectParameter("Id_Ter", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            var id_RikParameter = id_Rik.HasValue ?
                new ObjectParameter("Id_Rik", id_Rik) :
                new ObjectParameter("Id_Rik", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CapAcysDet>("spCapAcysDet_ConsultarPorProducto", id_EmpParameter, id_CdParameter, id_PrdParameter, id_TerParameter, id_CteParameter, id_RikParameter);
        }
    
        public virtual ObjectResult<CapAcysDet> spCapAcysDet_ConsultarPorProducto(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Prd, Nullable<int> id_Ter, Nullable<int> id_Cte, Nullable<int> id_Rik, MergeOption mergeOption)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_PrdParameter = id_Prd.HasValue ?
                new ObjectParameter("Id_Prd", id_Prd) :
                new ObjectParameter("Id_Prd", typeof(int));
    
            var id_TerParameter = id_Ter.HasValue ?
                new ObjectParameter("Id_Ter", id_Ter) :
                new ObjectParameter("Id_Ter", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            var id_RikParameter = id_Rik.HasValue ?
                new ObjectParameter("Id_Rik", id_Rik) :
                new ObjectParameter("Id_Rik", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CapAcysDet>("spCapAcysDet_ConsultarPorProducto", mergeOption, id_EmpParameter, id_CdParameter, id_PrdParameter, id_TerParameter, id_CteParameter, id_RikParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> spConsultarAcumuladoDeRemisiones(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Ter, Nullable<int> id_Cte)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_TerParameter = id_Ter.HasValue ?
                new ObjectParameter("Id_Ter", id_Ter) :
                new ObjectParameter("Id_Ter", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("spConsultarAcumuladoDeRemisiones", id_EmpParameter, id_CdParameter, id_TerParameter, id_CteParameter);
        }
    
        public virtual ObjectResult<CapRemision> spConsultarRemisionesEnPeriodo(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Ter, Nullable<int> id_Cte)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_TerParameter = id_Ter.HasValue ?
                new ObjectParameter("Id_Ter", id_Ter) :
                new ObjectParameter("Id_Ter", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CapRemision>("spConsultarRemisionesEnPeriodo", id_EmpParameter, id_CdParameter, id_TerParameter, id_CteParameter);
        }
    
        public virtual ObjectResult<CapRemision> spConsultarRemisionesEnPeriodo(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Ter, Nullable<int> id_Cte, MergeOption mergeOption)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_TerParameter = id_Ter.HasValue ?
                new ObjectParameter("Id_Ter", id_Ter) :
                new ObjectParameter("Id_Ter", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CapRemision>("spConsultarRemisionesEnPeriodo", mergeOption, id_EmpParameter, id_CdParameter, id_TerParameter, id_CteParameter);
        }
    
        public virtual ObjectResult<CapAcysDet> spCapAcysDet_ConsultarPorProductoYGarantia(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Prd, Nullable<int> id_Ter, Nullable<int> id_Cte, Nullable<int> id_Rik, Nullable<int> id_TG)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_PrdParameter = id_Prd.HasValue ?
                new ObjectParameter("Id_Prd", id_Prd) :
                new ObjectParameter("Id_Prd", typeof(int));
    
            var id_TerParameter = id_Ter.HasValue ?
                new ObjectParameter("Id_Ter", id_Ter) :
                new ObjectParameter("Id_Ter", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            var id_RikParameter = id_Rik.HasValue ?
                new ObjectParameter("Id_Rik", id_Rik) :
                new ObjectParameter("Id_Rik", typeof(int));
    
            var id_TGParameter = id_TG.HasValue ?
                new ObjectParameter("Id_TG", id_TG) :
                new ObjectParameter("Id_TG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CapAcysDet>("spCapAcysDet_ConsultarPorProductoYGarantia", id_EmpParameter, id_CdParameter, id_PrdParameter, id_TerParameter, id_CteParameter, id_RikParameter, id_TGParameter);
        }
    
        public virtual ObjectResult<CapAcysDet> spCapAcysDet_ConsultarPorProductoYGarantia(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Prd, Nullable<int> id_Ter, Nullable<int> id_Cte, Nullable<int> id_Rik, Nullable<int> id_TG, MergeOption mergeOption)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_PrdParameter = id_Prd.HasValue ?
                new ObjectParameter("Id_Prd", id_Prd) :
                new ObjectParameter("Id_Prd", typeof(int));
    
            var id_TerParameter = id_Ter.HasValue ?
                new ObjectParameter("Id_Ter", id_Ter) :
                new ObjectParameter("Id_Ter", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            var id_RikParameter = id_Rik.HasValue ?
                new ObjectParameter("Id_Rik", id_Rik) :
                new ObjectParameter("Id_Rik", typeof(int));
    
            var id_TGParameter = id_TG.HasValue ?
                new ObjectParameter("Id_TG", id_TG) :
                new ObjectParameter("Id_TG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CapAcysDet>("spCapAcysDet_ConsultarPorProductoYGarantia", mergeOption, id_EmpParameter, id_CdParameter, id_PrdParameter, id_TerParameter, id_CteParameter, id_RikParameter, id_TGParameter);
        }
    
        public virtual ObjectResult<spCapRemision_CalcularUtilidadPrimaReal_Result> spCapRemision_CalcularUtilidadPrimaReal(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Ter, Nullable<int> id_Cte, Nullable<int> id_TG, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_TerParameter = id_Ter.HasValue ?
                new ObjectParameter("Id_Ter", id_Ter) :
                new ObjectParameter("Id_Ter", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            var id_TGParameter = id_TG.HasValue ?
                new ObjectParameter("Id_TG", id_TG) :
                new ObjectParameter("Id_TG", typeof(int));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("fechaInicial", fechaInicial) :
                new ObjectParameter("fechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCapRemision_CalcularUtilidadPrimaReal_Result>("spCapRemision_CalcularUtilidadPrimaReal", id_EmpParameter, id_CdParameter, id_TerParameter, id_CteParameter, id_TGParameter, fechaInicialParameter, fechaFinalParameter);
        }
    
        public virtual ObjectResult<CapAcysDatosGarantia> spCapAcysDatosGarantia_Consultar(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Ter, Nullable<int> id_Cte, Nullable<int> id_TG)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_TerParameter = id_Ter.HasValue ?
                new ObjectParameter("Id_Ter", id_Ter) :
                new ObjectParameter("Id_Ter", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            var id_TGParameter = id_TG.HasValue ?
                new ObjectParameter("Id_TG", id_TG) :
                new ObjectParameter("Id_TG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CapAcysDatosGarantia>("spCapAcysDatosGarantia_Consultar", id_EmpParameter, id_CdParameter, id_TerParameter, id_CteParameter, id_TGParameter);
        }
    
        public virtual ObjectResult<CapAcysDatosGarantia> spCapAcysDatosGarantia_Consultar(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Ter, Nullable<int> id_Cte, Nullable<int> id_TG, MergeOption mergeOption)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_TerParameter = id_Ter.HasValue ?
                new ObjectParameter("Id_Ter", id_Ter) :
                new ObjectParameter("Id_Ter", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            var id_TGParameter = id_TG.HasValue ?
                new ObjectParameter("Id_TG", id_TG) :
                new ObjectParameter("Id_TG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CapAcysDatosGarantia>("spCapAcysDatosGarantia_Consultar", mergeOption, id_EmpParameter, id_CdParameter, id_TerParameter, id_CteParameter, id_TGParameter);
        }
    
        public virtual int spCapNotificacionesExcesoMeta_Insertar(Nullable<int> id_Emp, Nullable<int> id_Cd, string nem_Asunto, Nullable<System.DateTime> nem_FechaEnvio, string nem_Cuerpo, byte[] contenidoArchivoAdjunto)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var nem_AsuntoParameter = nem_Asunto != null ?
                new ObjectParameter("Nem_Asunto", nem_Asunto) :
                new ObjectParameter("Nem_Asunto", typeof(string));
    
            var nem_FechaEnvioParameter = nem_FechaEnvio.HasValue ?
                new ObjectParameter("Nem_FechaEnvio", nem_FechaEnvio) :
                new ObjectParameter("Nem_FechaEnvio", typeof(System.DateTime));
    
            var nem_CuerpoParameter = nem_Cuerpo != null ?
                new ObjectParameter("Nem_Cuerpo", nem_Cuerpo) :
                new ObjectParameter("Nem_Cuerpo", typeof(string));
    
            var contenidoArchivoAdjuntoParameter = contenidoArchivoAdjunto != null ?
                new ObjectParameter("contenidoArchivoAdjunto", contenidoArchivoAdjunto) :
                new ObjectParameter("contenidoArchivoAdjunto", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCapNotificacionesExcesoMeta_Insertar", id_EmpParameter, id_CdParameter, nem_AsuntoParameter, nem_FechaEnvioParameter, nem_CuerpoParameter, contenidoArchivoAdjuntoParameter);
        }
    
        public virtual ObjectResult<CapNotificacionExcesoMeta> spCapNotificacionesExcesoMeta_Consultar(Nullable<int> id_Emp, Nullable<int> id_Cd)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CapNotificacionExcesoMeta>("spCapNotificacionesExcesoMeta_Consultar", id_EmpParameter, id_CdParameter);
        }
    
        public virtual ObjectResult<CapNotificacionExcesoMeta> spCapNotificacionesExcesoMeta_Consultar(Nullable<int> id_Emp, Nullable<int> id_Cd, MergeOption mergeOption)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CapNotificacionExcesoMeta>("spCapNotificacionesExcesoMeta_Consultar", mergeOption, id_EmpParameter, id_CdParameter);
        }
    
        public virtual ObjectResult<CapRemision> spCatClienteDet_ObtenerRemisionesAbiertasPeriodoActual(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Cte, Nullable<int> id_Ter)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            var id_TerParameter = id_Ter.HasValue ?
                new ObjectParameter("Id_Ter", id_Ter) :
                new ObjectParameter("Id_Ter", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CapRemision>("spCatClienteDet_ObtenerRemisionesAbiertasPeriodoActual", id_EmpParameter, id_CdParameter, id_CteParameter, id_TerParameter);
        }
    
        public virtual ObjectResult<CapRemision> spCatClienteDet_ObtenerRemisionesAbiertasPeriodoActual(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Cte, Nullable<int> id_Ter, MergeOption mergeOption)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            var id_TerParameter = id_Ter.HasValue ?
                new ObjectParameter("Id_Ter", id_Ter) :
                new ObjectParameter("Id_Ter", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CapRemision>("spCatClienteDet_ObtenerRemisionesAbiertasPeriodoActual", mergeOption, id_EmpParameter, id_CdParameter, id_CteParameter, id_TerParameter);
        }
    
        public virtual int spCapAcys_ConsultaCte(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Cte, Nullable<int> id_Ter, Nullable<System.DateTime> fecha)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            var id_TerParameter = id_Ter.HasValue ?
                new ObjectParameter("Id_Ter", id_Ter) :
                new ObjectParameter("Id_Ter", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCapAcys_ConsultaCte", id_EmpParameter, id_CdParameter, id_CteParameter, id_TerParameter, fechaParameter);
        }
    
        public virtual ObjectResult<CatTipoGarantia> spCatTipoGarantia_ConsultarPorId(Nullable<int> id_TG)
        {
            var id_TGParameter = id_TG.HasValue ?
                new ObjectParameter("Id_TG", id_TG) :
                new ObjectParameter("Id_TG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatTipoGarantia>("spCatTipoGarantia_ConsultarPorId", id_TGParameter);
        }
    
        public virtual ObjectResult<CatTipoGarantia> spCatTipoGarantia_ConsultarPorId(Nullable<int> id_TG, MergeOption mergeOption)
        {
            var id_TGParameter = id_TG.HasValue ?
                new ObjectParameter("Id_TG", id_TG) :
                new ObjectParameter("Id_TG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatTipoGarantia>("spCatTipoGarantia_ConsultarPorId", mergeOption, id_TGParameter);
        }
    
        public virtual ObjectResult<CapConfiguracionGlobal> spCapConfiguracionGlobal_ConsultarPorLlave(string conf_llave)
        {
            var conf_llaveParameter = conf_llave != null ?
                new ObjectParameter("Conf_llave", conf_llave) :
                new ObjectParameter("Conf_llave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CapConfiguracionGlobal>("spCapConfiguracionGlobal_ConsultarPorLlave", conf_llaveParameter);
        }
    
        public virtual ObjectResult<CapConfiguracionGlobal> spCapConfiguracionGlobal_ConsultarPorLlave(string conf_llave, MergeOption mergeOption)
        {
            var conf_llaveParameter = conf_llave != null ?
                new ObjectParameter("Conf_llave", conf_llave) :
                new ObjectParameter("Conf_llave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CapConfiguracionGlobal>("spCapConfiguracionGlobal_ConsultarPorLlave", mergeOption, conf_llaveParameter);
        }
/*    
        public virtual ObjectResult<spCatCNac_DireccionesFiscales_Result> spCatCNac_DireccionesFiscales(string clienteSIAN)
        {
            var clienteSIANParameter = clienteSIAN != null ?
                new ObjectParameter("ClienteSIAN", clienteSIAN) :
                new ObjectParameter("ClienteSIAN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCatCNac_DireccionesFiscales_Result>("spCatCNac_DireccionesFiscales", clienteSIANParameter);
        }
*/
        public virtual ObjectResult<spCatCNac_DireccionesFiscales_Result> spCatCNac_DireccionesFiscales(string clienteSIAN, int id_Cd)
        {
            var clienteSIANParameter = clienteSIAN != null ?
                new ObjectParameter("ClienteSIAN", clienteSIAN) :
                new ObjectParameter("ClienteSIAN", typeof(string));

            var id_CdParameter = id_Cd != 0 ?
             new ObjectParameter("Id_Cd", id_Cd) :
             new ObjectParameter("Id_Cd", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCatCNac_DireccionesFiscales_Result>("spCatCNac_DireccionesFiscales2", clienteSIANParameter, id_CdParameter);
        }

        public virtual ObjectResult<spCNac_DatosACYSCN_Result> spCNac_DatosACYSCN(string clienteSIAN)
        {
            var clienteSIANParameter = clienteSIAN != null ?
                new ObjectParameter("ClienteSIAN", clienteSIAN) :
                new ObjectParameter("ClienteSIAN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCNac_DatosACYSCN_Result>("spCNac_DatosACYSCN", clienteSIANParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> spCNac_EsFranquicia(Nullable<int> id_Cd)
        {
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("spCNac_EsFranquicia", id_CdParameter);
        }
    
        public virtual ObjectResult<spCNac_EnviarSolicitudes_Sol_Result> spCNac_EnviarSolicitudes_Sol(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCNac_EnviarSolicitudes_Sol_Result>("spCNac_EnviarSolicitudes_Sol", idParameter);
        }
    
        public virtual ObjectResult<spCatCNac_ConsultarPedidosOC_Result> spCatCNac_ConsultarPedidosOC(Nullable<int> cliNum_Ini, Nullable<int> cliNum_Fin, Nullable<int> id_Ter_Ini, Nullable<int> id_Ter_Fin, Nullable<int> anio_Ini, Nullable<int> anio_Fin, string nom_Cliente, string estatus)
        {
            var cliNum_IniParameter = cliNum_Ini.HasValue ?
                new ObjectParameter("CliNum_Ini", cliNum_Ini) :
                new ObjectParameter("CliNum_Ini", typeof(int));
    
            var cliNum_FinParameter = cliNum_Fin.HasValue ?
                new ObjectParameter("CliNum_Fin", cliNum_Fin) :
                new ObjectParameter("CliNum_Fin", typeof(int));
    
            var id_Ter_IniParameter = id_Ter_Ini.HasValue ?
                new ObjectParameter("Id_Ter_Ini", id_Ter_Ini) :
                new ObjectParameter("Id_Ter_Ini", typeof(int));
    
            var id_Ter_FinParameter = id_Ter_Fin.HasValue ?
                new ObjectParameter("Id_Ter_Fin", id_Ter_Fin) :
                new ObjectParameter("Id_Ter_Fin", typeof(int));
    
            var anio_IniParameter = anio_Ini.HasValue ?
                new ObjectParameter("Anio_Ini", anio_Ini) :
                new ObjectParameter("Anio_Ini", typeof(int));
    
            var anio_FinParameter = anio_Fin.HasValue ?
                new ObjectParameter("Anio_Fin", anio_Fin) :
                new ObjectParameter("Anio_Fin", typeof(int));
    
            var nom_ClienteParameter = nom_Cliente != null ?
                new ObjectParameter("Nom_Cliente", nom_Cliente) :
                new ObjectParameter("Nom_Cliente", typeof(string));
    
            var estatusParameter = estatus != null ?
                new ObjectParameter("Estatus", estatus) :
                new ObjectParameter("Estatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCatCNac_ConsultarPedidosOC_Result>("spCatCNac_ConsultarPedidosOC", cliNum_IniParameter, cliNum_FinParameter, id_Ter_IniParameter, id_Ter_FinParameter, anio_IniParameter, anio_FinParameter, nom_ClienteParameter, estatusParameter);
        }
    
        public virtual ObjectResult<spCatCNac_ConsultaPedido_OC_Result> spCatCNac_ConsultaPedido_OC(Nullable<int> id_OC)
        {
            var id_OCParameter = id_OC.HasValue ?
                new ObjectParameter("id_OC", id_OC) :
                new ObjectParameter("id_OC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCatCNac_ConsultaPedido_OC_Result>("spCatCNac_ConsultaPedido_OC", id_OCParameter);
        }
    
        public virtual ObjectResult<spCatCNac_OrdenCompra_Detalle_Result> spCatCNac_OrdenCompra_Detalle(string idOC, Nullable<int> id_Cd, Nullable<int> id_Cte)
        {
            var idOCParameter = idOC != null ?
                new ObjectParameter("IdOC", idOC) :
                new ObjectParameter("IdOC", typeof(string));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCatCNac_OrdenCompra_Detalle_Result>("spCatCNac_OrdenCompra_Detalle", idOCParameter, id_CdParameter, id_CteParameter);
        }
    
        public virtual ObjectResult<spCatCNac_Remisiones80Ped_Result> spCatCNac_Remisiones80Ped(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCatCNac_Remisiones80Ped_Result>("spCatCNac_Remisiones80Ped", idParameter);
        }
    
        public virtual ObjectResult<spCatCNac_ValidaPedidoMov80_Result> spCatCNac_ValidaPedidoMov80(Nullable<int> id_Ped)
        {
            var id_PedParameter = id_Ped.HasValue ?
                new ObjectParameter("Id_Ped", id_Ped) :
                new ObjectParameter("Id_Ped", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCatCNac_ValidaPedidoMov80_Result>("spCatCNac_ValidaPedidoMov80", id_PedParameter);
        }
    
        public virtual ObjectResult<spCatCNac_ValidaClienteOC80_Result> spCatCNac_ValidaClienteOC80(Nullable<int> id_Emp, Nullable<int> id_Cd, Nullable<int> id_Cte)
        {
            var id_EmpParameter = id_Emp.HasValue ?
                new ObjectParameter("Id_Emp", id_Emp) :
                new ObjectParameter("Id_Emp", typeof(int));
    
            var id_CdParameter = id_Cd.HasValue ?
                new ObjectParameter("Id_Cd", id_Cd) :
                new ObjectParameter("Id_Cd", typeof(int));
    
            var id_CteParameter = id_Cte.HasValue ?
                new ObjectParameter("Id_Cte", id_Cte) :
                new ObjectParameter("Id_Cte", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCatCNac_ValidaClienteOC80_Result>("spCatCNac_ValidaClienteOC80", id_EmpParameter, id_CdParameter, id_CteParameter);
        }
    }
}
