//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.Web.Script.Serialization;
    using Newtonsoft.Json;
    //[Serializable]
    public partial class CapProyectoBiblioNodo
    {
        public CapProyectoBiblioNodo()
        {
            this.CapProyectoFaseBiblioNodoes = new HashSet<CapProyectoFaseBiblioNodo>();
        }
    
        public int Id_Emp { get; set; }
        public int Id_Cd { get; set; }
        public int Id_U { get; set; }
        public int Id_Biblioteca { get; set; }
        public int Id_Op { get; set; }
        public int Id_BiblioNodo { get; set; }
    
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual CapBibliotecaNodo CapBibliotecaNodo { get; set; }
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual CapBibliotecaUsuario CapBibliotecaUsuario { get; set; }
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual ICollection<CapProyectoFaseBiblioNodo> CapProyectoFaseBiblioNodoes { get; set; }
    }
}
