//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.Web.Script.Serialization;
    using Newtonsoft.Json;
    //[Serializable]
    public partial class CapValProyectoDet
    {
        public int Id_Emp { get; set; }
        public int Id_Cd { get; set; }
        public int Id_Vap { get; set; }
        public int Id_VapDet { get; set; }
        public int Vap_Tipo { get; set; }
        public long Id_Prd { get; set; }
        public int Vap_Cantidad { get; set; }
        public double Vap_Costo { get; set; }
        public double Vap_Precio { get; set; }
        public Nullable<System.DateTime> Det_FecAut { get; set; }
        public Nullable<int> Det_Autorizo { get; set; }
        public string Det_Estatus { get; set; }
        public Nullable<double> Det_PrecioLista { get; set; }
    }
}
