//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.Web.Script.Serialization;
    using Newtonsoft.Json;
    //[Serializable]
    public partial class CapValProyecto_Parametros
    {
        public int Id_Emp { get; set; }
        public int Id_Cd { get; set; }
        public int Id_Vap { get; set; }
        public Nullable<double> txtCuentasPorCobrar { get; set; }
        public Nullable<double> txtInventario { get; set; }
        public Nullable<double> txtGastosServirCliente { get; set; }
        public Nullable<double> txtVigencia { get; set; }
        public Nullable<double> txtFleteLocales { get; set; }
        public Nullable<double> txtIsr { get; set; }
        public Nullable<double> txtCetes { get; set; }
        public Nullable<double> txtFinanciamientoproveedores { get; set; }
        public Nullable<double> txtInversionactivosfijos { get; set; }
        public Nullable<double> txtCostodecapital { get; set; }
        public Nullable<double> txtManoObra { get; set; }
        public Nullable<double> txtGastosVarAplTerr { get; set; }
        public Nullable<double> txtFletesPagadosalCliente { get; set; }
    }
}
