//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.Web.Script.Serialization;
    using Newtonsoft.Json;
    //[Serializable]
    public partial class CatSolucion
    {
        public CatSolucion()
        {
            this.CrmOportunidadesProductos = new HashSet<CrmOportunidadesProducto>();
            this.CrmCatalogoUnicoes = new HashSet<CrmCatalogoUnico>();
            this.CatAplicacions = new HashSet<CatAplicacion>();
        }
    
        public int Id_Emp { get; set; }
        public int Id_Sol { get; set; }
        public string Sol_Descripcion { get; set; }
        public Nullable<int> Id_Area { get; set; }
        public Nullable<double> Sol_Potencial { get; set; }
        public Nullable<bool> Sol_Activo { get; set; }
    
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual ICollection<CrmOportunidadesProducto> CrmOportunidadesProductos { get; set; }
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual ICollection<CrmCatalogoUnico> CrmCatalogoUnicoes { get; set; }
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual CatEmpresa CatEmpresa { get; set; }
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual CatArea CatArea { get; set; }
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual ICollection<CatAplicacion> CatAplicacions { get; set; }
    }
}
