//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.Web.Script.Serialization;
    using Newtonsoft.Json;
    //[Serializable]
    public partial class CatUEN
    {
        public CatUEN()
        {
            this.CatSegmentos = new HashSet<CatSegmento>();
            this.CrmOportunidadesProductos = new HashSet<CrmOportunidadesProducto>();
            this.CatClientes = new HashSet<CatCliente>();
            this.CrmCatalogoUnicoes = new HashSet<CrmCatalogoUnico>();
            this.CatTerritorios = new HashSet<CatTerritorio>();
        }
    
        public int Id_Emp { get; set; }
        public int Id_Uen { get; set; }
        public string Uen_Descripcion { get; set; }
        public Nullable<bool> Uen_Activo { get; set; }
        public Nullable<int> Id_U { get; set; }
    
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual ICollection<CatSegmento> CatSegmentos { get; set; }
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual ICollection<CrmOportunidadesProducto> CrmOportunidadesProductos { get; set; }
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual ICollection<CatCliente> CatClientes { get; set; }
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual ICollection<CrmCatalogoUnico> CrmCatalogoUnicoes { get; set; }
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual CatEmpresa CatEmpresa { get; set; }
    	[IgnoreDataMember]
    	[ScriptIgnore]
    	[JsonIgnore]
        public virtual ICollection<CatTerritorio> CatTerritorios { get; set; }
    }
}
