//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaModelo
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.Web.Script.Serialization;
    using Newtonsoft.Json;
    //[Serializable]
    public partial class SysConfiguracion
    {
        public int Id_Emp { get; set; }
        public int Id_Cd { get; set; }
        public int Id_Conf { get; set; }
        public string Conf_Valor { get; set; }
        public string Conf_Descripcion { get; set; }
    }
}
