//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIANWEB.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://13.84.212.41/wssianweb/Service1.asmx")]
        public string SIANWEB_sian_cfd_Service2 {
            get {
                return ((string)(this["SIANWEB_sian_cfd_Service2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://148.244.244.207/wssianbennetts/Service1.asmx")]
        public string SIANWEB_WebReference_Service1 {
            get {
                return ((string)(this["SIANWEB_WebReference_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://13.84.212.41/wssianweb/service1.asmx")]
        public string SIANWEB_sian_cfd_Service1 {
            get {
                return ((string)(this["SIANWEB_sian_cfd_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://207.248.253.104/OrdenCompra/Service1.asmx")]
        public string SIANWEB_OrdendeCompra_Service1 {
            get {
                return ((string)(this["SIANWEB_OrdendeCompra_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://207.248.253.104/wsmacola/wsmacola.asmx")]
        public string SIANWEB_WsMacola_wsMacola {
            get {
                return ((string)(this["SIANWEB_WsMacola_wsMacola"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://40.124.41.101/ImprimeRemision/service1.asmx")]
        public string SIANWEB_RemElectronica_Service1 {
            get {
                return ((string)(this["SIANWEB_RemElectronica_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:6846/Service1.asmx")]
        public string SIANWEB_WS_PagosExternos_Service1 {
            get {
                return ((string)(this["SIANWEB_WS_PagosExternos_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://40.124.41.101/wsProductoCN/Service1.asmx")]
        public string SIANWEB_WS_Producto_Service1 {
            get {
                return ((string)(this["SIANWEB_WS_Producto_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://40.124.41.101/GuardaRemision/Service1.asmx")]
        public string SIANWEB_WS_RemElectronicaCtaNacional_Service1 {
            get {
                return ((string)(this["SIANWEB_WS_RemElectronicaCtaNacional_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://40.124.41.101/wsCuentaNacional/Service1.asmx")]
        public string SIANWEB_WS_CuentaNacional_Service1 {
            get {
                return ((string)(this["SIANWEB_WS_CuentaNacional_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://40.124.41.101/wsCuentaNacional/EnviaCuentaNacional.asmx")]
        public string SIANWEB_EnviaCuentaNacional_EnviaCuentaNacional {
            get {
                return ((string)(this["SIANWEB_EnviaCuentaNacional_EnviaCuentaNacional"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://40.84.229.61/wsClienteTerritorio/Service1.asmx")]
        public string SIANWEB_wsTerritorio_Service1 {
            get {
                return ((string)(this["SIANWEB_wsTerritorio_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://40.124.41.101/wsBuzonWeb/wsBuzonWeb.asmx")]
        public string SIANWEB_wsBuzonWeb_wsBuzonWeb {
            get {
                return ((string)(this["SIANWEB_wsBuzonWeb_wsBuzonWeb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://40.124.41.101/wssgcup/Service1.asmx")]
        public string SIANWEB_wsCatalogoUnico_Service1 {
            get {
                return ((string)(this["SIANWEB_wsCatalogoUnico_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://40.124.41.101/CFDPDF_PRUEBA/")]
        public string Ruta_Impresion_PDF {
            get {
                return ((string)(this["Ruta_Impresion_PDF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://40.124.41.101/CFDXML/")]
        public string Ruta_Impresion_XML {
            get {
                return ((string)(this["Ruta_Impresion_XML"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Factura")]
        public string Ruta_Impresion_TipoDoc {
            get {
                return ((string)(this["Ruta_Impresion_TipoDoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://40.84.229.61/wsquejas/Service1.asmx")]
        public string SIANWEB_wsQuejas_Service1 {
            get {
                return ((string)(this["SIANWEB_wsQuejas_Service1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://axservidor/keyfac/Service1.asmx")]
        public string SIANWEB_sian_cfd_Service3 {
            get {
                return ((string)(this["SIANWEB_sian_cfd_Service3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://40.124.41.101/wslistaprecios/wsListaPrecios.asmx")]
        public string SIANWEB_wsListaPrecios_wsListaPrecios {
            get {
                return ((string)(this["SIANWEB_wsListaPrecios_wsListaPrecios"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://40.124.41.101/WSCancelacion/service1.asmx")]
        public string SIANWEB_WS_CFDICancelacion_Service1 {
            get {
                return ((string)(this["SIANWEB_WS_CFDICancelacion_Service1"]));
            }
        }
    }
}
