//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SIANWEB.wsListaPrecios {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsListaPreciosSoap", Namespace="http://tempuri.org/")]
    public partial class wsListaPrecios : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetPriceListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListaActualizadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAplicacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSubFamiliasOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTipoProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProveedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCampoListaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConfiguraListasOperationCompleted;
        
        private System.Threading.SendOrPostCallback PutHabilitarListaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPrecioPorAplicarOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPrecioIncidenciasOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPrecioLogEventosOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFechaUltModOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKeyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsListaPrecios() {
            this.Url = global::SIANWEB.Properties.Settings.Default.SIANWEB_wsListaPrecios_wsListaPrecios;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPriceListCompletedEventHandler GetPriceListCompleted;
        
        /// <remarks/>
        public event GetListaActualizadaCompletedEventHandler GetListaActualizadaCompleted;
        
        /// <remarks/>
        public event GetAplicacionCompletedEventHandler GetAplicacionCompleted;
        
        /// <remarks/>
        public event GetSubFamiliasCompletedEventHandler GetSubFamiliasCompleted;
        
        /// <remarks/>
        public event GetTipoProductoCompletedEventHandler GetTipoProductoCompleted;
        
        /// <remarks/>
        public event GetProveedorCompletedEventHandler GetProveedorCompleted;
        
        /// <remarks/>
        public event GetCampoListaCompletedEventHandler GetCampoListaCompleted;
        
        /// <remarks/>
        public event GetConfiguraListasCompletedEventHandler GetConfiguraListasCompleted;
        
        /// <remarks/>
        public event PutHabilitarListaCompletedEventHandler PutHabilitarListaCompleted;
        
        /// <remarks/>
        public event GetPrecioPorAplicarCompletedEventHandler GetPrecioPorAplicarCompleted;
        
        /// <remarks/>
        public event GetPrecioIncidenciasCompletedEventHandler GetPrecioIncidenciasCompleted;
        
        /// <remarks/>
        public event GetPrecioLogEventosCompletedEventHandler GetPrecioLogEventosCompleted;
        
        /// <remarks/>
        public event GetFechaUltModCompletedEventHandler GetFechaUltModCompleted;
        
        /// <remarks/>
        public event GetKeyCompletedEventHandler GetKeyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPriceList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaPrecios[] GetPriceList(string strLoginKey, string aplicacion, string subfamilia, string tipoproducto, string proveedor, string palabraclave, string lista, string id_Prd) {
            object[] results = this.Invoke("GetPriceList", new object[] {
                        strLoginKey,
                        aplicacion,
                        subfamilia,
                        tipoproducto,
                        proveedor,
                        palabraclave,
                        lista,
                        id_Prd});
            return ((ListaPrecios[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPriceListAsync(string strLoginKey, string aplicacion, string subfamilia, string tipoproducto, string proveedor, string palabraclave, string lista, string id_Prd) {
            this.GetPriceListAsync(strLoginKey, aplicacion, subfamilia, tipoproducto, proveedor, palabraclave, lista, id_Prd, null);
        }
        
        /// <remarks/>
        public void GetPriceListAsync(string strLoginKey, string aplicacion, string subfamilia, string tipoproducto, string proveedor, string palabraclave, string lista, string id_Prd, object userState) {
            if ((this.GetPriceListOperationCompleted == null)) {
                this.GetPriceListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPriceListOperationCompleted);
            }
            this.InvokeAsync("GetPriceList", new object[] {
                        strLoginKey,
                        aplicacion,
                        subfamilia,
                        tipoproducto,
                        proveedor,
                        palabraclave,
                        lista,
                        id_Prd}, this.GetPriceListOperationCompleted, userState);
        }
        
        private void OnGetPriceListOperationCompleted(object arg) {
            if ((this.GetPriceListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPriceListCompleted(this, new GetPriceListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListaActualizada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaPrecios[] GetListaActualizada(string strLoginKey, int listacosto, int opcion) {
            object[] results = this.Invoke("GetListaActualizada", new object[] {
                        strLoginKey,
                        listacosto,
                        opcion});
            return ((ListaPrecios[])(results[0]));
        }
        
        /// <remarks/>
        public void GetListaActualizadaAsync(string strLoginKey, int listacosto, int opcion) {
            this.GetListaActualizadaAsync(strLoginKey, listacosto, opcion, null);
        }
        
        /// <remarks/>
        public void GetListaActualizadaAsync(string strLoginKey, int listacosto, int opcion, object userState) {
            if ((this.GetListaActualizadaOperationCompleted == null)) {
                this.GetListaActualizadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListaActualizadaOperationCompleted);
            }
            this.InvokeAsync("GetListaActualizada", new object[] {
                        strLoginKey,
                        listacosto,
                        opcion}, this.GetListaActualizadaOperationCompleted, userState);
        }
        
        private void OnGetListaActualizadaOperationCompleted(object arg) {
            if ((this.GetListaActualizadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListaActualizadaCompleted(this, new GetListaActualizadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAplicacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CatalogoListaPrecios[] GetAplicacion(string strLoginKey) {
            object[] results = this.Invoke("GetAplicacion", new object[] {
                        strLoginKey});
            return ((CatalogoListaPrecios[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAplicacionAsync(string strLoginKey) {
            this.GetAplicacionAsync(strLoginKey, null);
        }
        
        /// <remarks/>
        public void GetAplicacionAsync(string strLoginKey, object userState) {
            if ((this.GetAplicacionOperationCompleted == null)) {
                this.GetAplicacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAplicacionOperationCompleted);
            }
            this.InvokeAsync("GetAplicacion", new object[] {
                        strLoginKey}, this.GetAplicacionOperationCompleted, userState);
        }
        
        private void OnGetAplicacionOperationCompleted(object arg) {
            if ((this.GetAplicacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAplicacionCompleted(this, new GetAplicacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSubFamilias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CatalogoListaPrecios[] GetSubFamilias(string strLoginKey, int id_SubCatalogo_Relacionado) {
            object[] results = this.Invoke("GetSubFamilias", new object[] {
                        strLoginKey,
                        id_SubCatalogo_Relacionado});
            return ((CatalogoListaPrecios[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSubFamiliasAsync(string strLoginKey, int id_SubCatalogo_Relacionado) {
            this.GetSubFamiliasAsync(strLoginKey, id_SubCatalogo_Relacionado, null);
        }
        
        /// <remarks/>
        public void GetSubFamiliasAsync(string strLoginKey, int id_SubCatalogo_Relacionado, object userState) {
            if ((this.GetSubFamiliasOperationCompleted == null)) {
                this.GetSubFamiliasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSubFamiliasOperationCompleted);
            }
            this.InvokeAsync("GetSubFamilias", new object[] {
                        strLoginKey,
                        id_SubCatalogo_Relacionado}, this.GetSubFamiliasOperationCompleted, userState);
        }
        
        private void OnGetSubFamiliasOperationCompleted(object arg) {
            if ((this.GetSubFamiliasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSubFamiliasCompleted(this, new GetSubFamiliasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTipoProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CatalogoListaPrecios[] GetTipoProducto(string strLoginKey) {
            object[] results = this.Invoke("GetTipoProducto", new object[] {
                        strLoginKey});
            return ((CatalogoListaPrecios[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTipoProductoAsync(string strLoginKey) {
            this.GetTipoProductoAsync(strLoginKey, null);
        }
        
        /// <remarks/>
        public void GetTipoProductoAsync(string strLoginKey, object userState) {
            if ((this.GetTipoProductoOperationCompleted == null)) {
                this.GetTipoProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTipoProductoOperationCompleted);
            }
            this.InvokeAsync("GetTipoProducto", new object[] {
                        strLoginKey}, this.GetTipoProductoOperationCompleted, userState);
        }
        
        private void OnGetTipoProductoOperationCompleted(object arg) {
            if ((this.GetTipoProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTipoProductoCompleted(this, new GetTipoProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProveedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CatalogoListaPrecios[] GetProveedor(string strLoginKey) {
            object[] results = this.Invoke("GetProveedor", new object[] {
                        strLoginKey});
            return ((CatalogoListaPrecios[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProveedorAsync(string strLoginKey) {
            this.GetProveedorAsync(strLoginKey, null);
        }
        
        /// <remarks/>
        public void GetProveedorAsync(string strLoginKey, object userState) {
            if ((this.GetProveedorOperationCompleted == null)) {
                this.GetProveedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProveedorOperationCompleted);
            }
            this.InvokeAsync("GetProveedor", new object[] {
                        strLoginKey}, this.GetProveedorOperationCompleted, userState);
        }
        
        private void OnGetProveedorOperationCompleted(object arg) {
            if ((this.GetProveedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProveedorCompleted(this, new GetProveedorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCampoLista", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CatalogoListaPrecios[] GetCampoLista(string strLoginKey) {
            object[] results = this.Invoke("GetCampoLista", new object[] {
                        strLoginKey});
            return ((CatalogoListaPrecios[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCampoListaAsync(string strLoginKey) {
            this.GetCampoListaAsync(strLoginKey, null);
        }
        
        /// <remarks/>
        public void GetCampoListaAsync(string strLoginKey, object userState) {
            if ((this.GetCampoListaOperationCompleted == null)) {
                this.GetCampoListaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCampoListaOperationCompleted);
            }
            this.InvokeAsync("GetCampoLista", new object[] {
                        strLoginKey}, this.GetCampoListaOperationCompleted, userState);
        }
        
        private void OnGetCampoListaOperationCompleted(object arg) {
            if ((this.GetCampoListaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCampoListaCompleted(this, new GetCampoListaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetConfiguraListas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CatalogoListaPrecios[] GetConfiguraListas(string strLoginKey) {
            object[] results = this.Invoke("GetConfiguraListas", new object[] {
                        strLoginKey});
            return ((CatalogoListaPrecios[])(results[0]));
        }
        
        /// <remarks/>
        public void GetConfiguraListasAsync(string strLoginKey) {
            this.GetConfiguraListasAsync(strLoginKey, null);
        }
        
        /// <remarks/>
        public void GetConfiguraListasAsync(string strLoginKey, object userState) {
            if ((this.GetConfiguraListasOperationCompleted == null)) {
                this.GetConfiguraListasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConfiguraListasOperationCompleted);
            }
            this.InvokeAsync("GetConfiguraListas", new object[] {
                        strLoginKey}, this.GetConfiguraListasOperationCompleted, userState);
        }
        
        private void OnGetConfiguraListasOperationCompleted(object arg) {
            if ((this.GetConfiguraListasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConfiguraListasCompleted(this, new GetConfiguraListasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PutHabilitarLista", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PutHabilitarLista(string strLoginKey, int id_SubCatalogo, int idhabilitar, int habilitasiancentral, int id_usuario) {
            object[] results = this.Invoke("PutHabilitarLista", new object[] {
                        strLoginKey,
                        id_SubCatalogo,
                        idhabilitar,
                        habilitasiancentral,
                        id_usuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PutHabilitarListaAsync(string strLoginKey, int id_SubCatalogo, int idhabilitar, int habilitasiancentral, int id_usuario) {
            this.PutHabilitarListaAsync(strLoginKey, id_SubCatalogo, idhabilitar, habilitasiancentral, id_usuario, null);
        }
        
        /// <remarks/>
        public void PutHabilitarListaAsync(string strLoginKey, int id_SubCatalogo, int idhabilitar, int habilitasiancentral, int id_usuario, object userState) {
            if ((this.PutHabilitarListaOperationCompleted == null)) {
                this.PutHabilitarListaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPutHabilitarListaOperationCompleted);
            }
            this.InvokeAsync("PutHabilitarLista", new object[] {
                        strLoginKey,
                        id_SubCatalogo,
                        idhabilitar,
                        habilitasiancentral,
                        id_usuario}, this.PutHabilitarListaOperationCompleted, userState);
        }
        
        private void OnPutHabilitarListaOperationCompleted(object arg) {
            if ((this.PutHabilitarListaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PutHabilitarListaCompleted(this, new PutHabilitarListaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPrecioPorAplicar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaPrecios[] GetPrecioPorAplicar(string strLoginKey, string palabraclave, System.DateTime fechainicial, System.DateTime fechafinal, string id_Prd, int todohistorial) {
            object[] results = this.Invoke("GetPrecioPorAplicar", new object[] {
                        strLoginKey,
                        palabraclave,
                        fechainicial,
                        fechafinal,
                        id_Prd,
                        todohistorial});
            return ((ListaPrecios[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPrecioPorAplicarAsync(string strLoginKey, string palabraclave, System.DateTime fechainicial, System.DateTime fechafinal, string id_Prd, int todohistorial) {
            this.GetPrecioPorAplicarAsync(strLoginKey, palabraclave, fechainicial, fechafinal, id_Prd, todohistorial, null);
        }
        
        /// <remarks/>
        public void GetPrecioPorAplicarAsync(string strLoginKey, string palabraclave, System.DateTime fechainicial, System.DateTime fechafinal, string id_Prd, int todohistorial, object userState) {
            if ((this.GetPrecioPorAplicarOperationCompleted == null)) {
                this.GetPrecioPorAplicarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPrecioPorAplicarOperationCompleted);
            }
            this.InvokeAsync("GetPrecioPorAplicar", new object[] {
                        strLoginKey,
                        palabraclave,
                        fechainicial,
                        fechafinal,
                        id_Prd,
                        todohistorial}, this.GetPrecioPorAplicarOperationCompleted, userState);
        }
        
        private void OnGetPrecioPorAplicarOperationCompleted(object arg) {
            if ((this.GetPrecioPorAplicarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPrecioPorAplicarCompleted(this, new GetPrecioPorAplicarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPrecioIncidencias", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaPreciosIncidencias[] GetPrecioIncidencias(string strLoginKey, string palabraclave, System.DateTime fechainicial, System.DateTime fechafinal, string id_Prd, int todohistorial) {
            object[] results = this.Invoke("GetPrecioIncidencias", new object[] {
                        strLoginKey,
                        palabraclave,
                        fechainicial,
                        fechafinal,
                        id_Prd,
                        todohistorial});
            return ((ListaPreciosIncidencias[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPrecioIncidenciasAsync(string strLoginKey, string palabraclave, System.DateTime fechainicial, System.DateTime fechafinal, string id_Prd, int todohistorial) {
            this.GetPrecioIncidenciasAsync(strLoginKey, palabraclave, fechainicial, fechafinal, id_Prd, todohistorial, null);
        }
        
        /// <remarks/>
        public void GetPrecioIncidenciasAsync(string strLoginKey, string palabraclave, System.DateTime fechainicial, System.DateTime fechafinal, string id_Prd, int todohistorial, object userState) {
            if ((this.GetPrecioIncidenciasOperationCompleted == null)) {
                this.GetPrecioIncidenciasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPrecioIncidenciasOperationCompleted);
            }
            this.InvokeAsync("GetPrecioIncidencias", new object[] {
                        strLoginKey,
                        palabraclave,
                        fechainicial,
                        fechafinal,
                        id_Prd,
                        todohistorial}, this.GetPrecioIncidenciasOperationCompleted, userState);
        }
        
        private void OnGetPrecioIncidenciasOperationCompleted(object arg) {
            if ((this.GetPrecioIncidenciasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPrecioIncidenciasCompleted(this, new GetPrecioIncidenciasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPrecioLogEventos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaPreciosIncidencias[] GetPrecioLogEventos(string strLoginKey, string palabraclave, System.DateTime fechainicial, System.DateTime fechafinal, string id_Prd, int todohistorial) {
            object[] results = this.Invoke("GetPrecioLogEventos", new object[] {
                        strLoginKey,
                        palabraclave,
                        fechainicial,
                        fechafinal,
                        id_Prd,
                        todohistorial});
            return ((ListaPreciosIncidencias[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPrecioLogEventosAsync(string strLoginKey, string palabraclave, System.DateTime fechainicial, System.DateTime fechafinal, string id_Prd, int todohistorial) {
            this.GetPrecioLogEventosAsync(strLoginKey, palabraclave, fechainicial, fechafinal, id_Prd, todohistorial, null);
        }
        
        /// <remarks/>
        public void GetPrecioLogEventosAsync(string strLoginKey, string palabraclave, System.DateTime fechainicial, System.DateTime fechafinal, string id_Prd, int todohistorial, object userState) {
            if ((this.GetPrecioLogEventosOperationCompleted == null)) {
                this.GetPrecioLogEventosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPrecioLogEventosOperationCompleted);
            }
            this.InvokeAsync("GetPrecioLogEventos", new object[] {
                        strLoginKey,
                        palabraclave,
                        fechainicial,
                        fechafinal,
                        id_Prd,
                        todohistorial}, this.GetPrecioLogEventosOperationCompleted, userState);
        }
        
        private void OnGetPrecioLogEventosOperationCompleted(object arg) {
            if ((this.GetPrecioLogEventosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPrecioLogEventosCompleted(this, new GetPrecioLogEventosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFechaUltMod", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime GetFechaUltMod(string strLoginKey, string palabraclave) {
            object[] results = this.Invoke("GetFechaUltMod", new object[] {
                        strLoginKey,
                        palabraclave});
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void GetFechaUltModAsync(string strLoginKey, string palabraclave) {
            this.GetFechaUltModAsync(strLoginKey, palabraclave, null);
        }
        
        /// <remarks/>
        public void GetFechaUltModAsync(string strLoginKey, string palabraclave, object userState) {
            if ((this.GetFechaUltModOperationCompleted == null)) {
                this.GetFechaUltModOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFechaUltModOperationCompleted);
            }
            this.InvokeAsync("GetFechaUltMod", new object[] {
                        strLoginKey,
                        palabraclave}, this.GetFechaUltModOperationCompleted, userState);
        }
        
        private void OnGetFechaUltModOperationCompleted(object arg) {
            if ((this.GetFechaUltModCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFechaUltModCompleted(this, new GetFechaUltModCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetKey", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetKey() {
            object[] results = this.Invoke("GetKey", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetKeyAsync() {
            this.GetKeyAsync(null);
        }
        
        /// <remarks/>
        public void GetKeyAsync(object userState) {
            if ((this.GetKeyOperationCompleted == null)) {
                this.GetKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKeyOperationCompleted);
            }
            this.InvokeAsync("GetKey", new object[0], this.GetKeyOperationCompleted, userState);
        }
        
        private void OnGetKeyOperationCompleted(object arg) {
            if ((this.GetKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKeyCompleted(this, new GetKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaPrecios {
        
        private System.Nullable<long> id_PrdField;
        
        private string descripcionField;
        
        private string eSTATUSField;
        
        private string aPLICACIONField;
        
        private string sUBFAMILIAField;
        
        private string tIPOPRODUCTOField;
        
        private string lISTADEPRECIOSField;
        
        private string nOPROVEEDORField;
        
        private string nOMBREPROVEEDORField;
        
        private string nODEARTDEPROVEEDORField;
        
        private System.Nullable<decimal> pAAAACTUALField;
        
        private System.Nullable<decimal> pLISTAACTUALField;
        
        private System.Nullable<decimal> pAAAAnteriorField;
        
        private System.Nullable<decimal> pLISTAANTERIORField;
        
        private System.Nullable<decimal> pAAAFUTURAField;
        
        private System.Nullable<decimal> pLISTAFUTURAField;
        
        private System.Nullable<decimal> pVariacionPAAAField;
        
        private System.Nullable<decimal> pVariacionPLISTAField;
        
        private System.Nullable<System.DateTime> fECHAINICIOVIGField;
        
        private System.Nullable<System.DateTime> fECHAFINVIGField;
        
        private int tIENEPRECIOFUTUROField;
        
        private string rESPONSABLEField;
        
        private string pLANEACIONField;
        
        private System.Nullable<decimal> margenredField;
        
        private System.Nullable<System.DateTime> fECHAINICIOVIGFUTField;
        
        private System.Nullable<System.DateTime> fECHAFINVIGFUTField;
        
        private string mONEDAField;
        
        private System.Nullable<decimal> costoEstandardField;
        
        private System.Nullable<decimal> precioBaseField;
        
        private string presentacionField;
        
        private System.Nullable<decimal> unidaddeVentaField;
        
        private System.Nullable<decimal> pVariacionPAAAFUTUROField;
        
        private System.Nullable<decimal> pVariacionPLISTAFUTUROField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Id_Prd {
            get {
                return this.id_PrdField;
            }
            set {
                this.id_PrdField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string ESTATUS {
            get {
                return this.eSTATUSField;
            }
            set {
                this.eSTATUSField = value;
            }
        }
        
        /// <remarks/>
        public string APLICACION {
            get {
                return this.aPLICACIONField;
            }
            set {
                this.aPLICACIONField = value;
            }
        }
        
        /// <remarks/>
        public string SUBFAMILIA {
            get {
                return this.sUBFAMILIAField;
            }
            set {
                this.sUBFAMILIAField = value;
            }
        }
        
        /// <remarks/>
        public string TIPOPRODUCTO {
            get {
                return this.tIPOPRODUCTOField;
            }
            set {
                this.tIPOPRODUCTOField = value;
            }
        }
        
        /// <remarks/>
        public string LISTADEPRECIOS {
            get {
                return this.lISTADEPRECIOSField;
            }
            set {
                this.lISTADEPRECIOSField = value;
            }
        }
        
        /// <remarks/>
        public string NOPROVEEDOR {
            get {
                return this.nOPROVEEDORField;
            }
            set {
                this.nOPROVEEDORField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBREPROVEEDOR {
            get {
                return this.nOMBREPROVEEDORField;
            }
            set {
                this.nOMBREPROVEEDORField = value;
            }
        }
        
        /// <remarks/>
        public string NODEARTDEPROVEEDOR {
            get {
                return this.nODEARTDEPROVEEDORField;
            }
            set {
                this.nODEARTDEPROVEEDORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PAAAACTUAL {
            get {
                return this.pAAAACTUALField;
            }
            set {
                this.pAAAACTUALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PLISTAACTUAL {
            get {
                return this.pLISTAACTUALField;
            }
            set {
                this.pLISTAACTUALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PAAAAnterior {
            get {
                return this.pAAAAnteriorField;
            }
            set {
                this.pAAAAnteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PLISTAANTERIOR {
            get {
                return this.pLISTAANTERIORField;
            }
            set {
                this.pLISTAANTERIORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PAAAFUTURA {
            get {
                return this.pAAAFUTURAField;
            }
            set {
                this.pAAAFUTURAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PLISTAFUTURA {
            get {
                return this.pLISTAFUTURAField;
            }
            set {
                this.pLISTAFUTURAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PVariacionPAAA {
            get {
                return this.pVariacionPAAAField;
            }
            set {
                this.pVariacionPAAAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PVariacionPLISTA {
            get {
                return this.pVariacionPLISTAField;
            }
            set {
                this.pVariacionPLISTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FECHAINICIOVIG {
            get {
                return this.fECHAINICIOVIGField;
            }
            set {
                this.fECHAINICIOVIGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FECHAFINVIG {
            get {
                return this.fECHAFINVIGField;
            }
            set {
                this.fECHAFINVIGField = value;
            }
        }
        
        /// <remarks/>
        public int TIENEPRECIOFUTURO {
            get {
                return this.tIENEPRECIOFUTUROField;
            }
            set {
                this.tIENEPRECIOFUTUROField = value;
            }
        }
        
        /// <remarks/>
        public string RESPONSABLE {
            get {
                return this.rESPONSABLEField;
            }
            set {
                this.rESPONSABLEField = value;
            }
        }
        
        /// <remarks/>
        public string PLANEACION {
            get {
                return this.pLANEACIONField;
            }
            set {
                this.pLANEACIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> margenred {
            get {
                return this.margenredField;
            }
            set {
                this.margenredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FECHAINICIOVIGFUT {
            get {
                return this.fECHAINICIOVIGFUTField;
            }
            set {
                this.fECHAINICIOVIGFUTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FECHAFINVIGFUT {
            get {
                return this.fECHAFINVIGFUTField;
            }
            set {
                this.fECHAFINVIGFUTField = value;
            }
        }
        
        /// <remarks/>
        public string MONEDA {
            get {
                return this.mONEDAField;
            }
            set {
                this.mONEDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> CostoEstandard {
            get {
                return this.costoEstandardField;
            }
            set {
                this.costoEstandardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PrecioBase {
            get {
                return this.precioBaseField;
            }
            set {
                this.precioBaseField = value;
            }
        }
        
        /// <remarks/>
        public string Presentacion {
            get {
                return this.presentacionField;
            }
            set {
                this.presentacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> UnidaddeVenta {
            get {
                return this.unidaddeVentaField;
            }
            set {
                this.unidaddeVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PVariacionPAAAFUTURO {
            get {
                return this.pVariacionPAAAFUTUROField;
            }
            set {
                this.pVariacionPAAAFUTUROField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PVariacionPLISTAFUTURO {
            get {
                return this.pVariacionPLISTAFUTUROField;
            }
            set {
                this.pVariacionPLISTAFUTUROField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaPreciosIncidencias {
        
        private System.Nullable<int> id_CifrasControlField;
        
        private System.Nullable<int> id_ListaHistoricoField;
        
        private System.Nullable<int> id_ListaCostoField;
        
        private System.Nullable<int> id_ListaCostoDetField;
        
        private System.Nullable<long> id_PrdField;
        
        private System.Nullable<int> vigenteField;
        
        private string descripcionField;
        
        private string nOMBREDEPROVEEDORField;
        
        private string nODEARTDEPROVEEDORField;
        
        private System.Nullable<System.DateTime> fecha_InicioField;
        
        private System.Nullable<System.DateTime> fecha_FinField;
        
        private System.Nullable<decimal> oRIGINALCOSTODECOMPRAField;
        
        private System.Nullable<decimal> cOSTODECOMPRAField;
        
        private System.Nullable<decimal> aCTUALIZADOCOSTODECOMPRAField;
        
        private System.Nullable<decimal> oRIGINALPRECIOMINIMODEVENTAField;
        
        private System.Nullable<decimal> pRECIOMINIMODEVENTAField;
        
        private System.Nullable<decimal> aCTUALIZADOPRECIOMINIMODEVENTAField;
        
        private System.Nullable<decimal> oRIGINALCOSTODOLARESField;
        
        private System.Nullable<decimal> cOSTODOLARESField;
        
        private System.Nullable<decimal> aCTUALIZADOCOSTODOLARESField;
        
        private System.Nullable<decimal> oRIGINALPAAAField;
        
        private System.Nullable<decimal> pAAAField;
        
        private System.Nullable<decimal> aCTUALIZADOPAAAField;
        
        private System.Nullable<decimal> oRIGINALPLISTAField;
        
        private System.Nullable<decimal> pLISTAField;
        
        private System.Nullable<decimal> aCTUALIZADOPLISTAField;
        
        private System.Nullable<decimal> oRIGINALPrecioBaseField;
        
        private System.Nullable<decimal> preciobaseField;
        
        private System.Nullable<decimal> aCTUALIZADOPrecioBaseField;
        
        private System.Nullable<decimal> oRIGINALPAAAANTERIORField;
        
        private System.Nullable<decimal> pAAAANTERIORField;
        
        private System.Nullable<decimal> aCTUALIZADOPAAAANTERIORField;
        
        private System.Nullable<decimal> oRIGINALPLISTAANTERIORField;
        
        private System.Nullable<decimal> pLISTAANTERIORField;
        
        private System.Nullable<decimal> aCTUALIZADOPLISTAANTERIORField;
        
        private System.Nullable<decimal> oRIGINALCOSTOestandardField;
        
        private System.Nullable<decimal> costoestandardField;
        
        private System.Nullable<decimal> aCTUALIZADOCOSTOestandardField;
        
        private System.Nullable<decimal> oRIGINALCOSTODECOMPRA_COMPRASField;
        
        private System.Nullable<decimal> cOSTODECOMPRA_COMPRASField;
        
        private System.Nullable<decimal> aCTUALIZADOCOSTODECOMPRA_COMPRASField;
        
        private System.Nullable<decimal> oRIGINALCOSTOPROYECTADOENMNField;
        
        private System.Nullable<decimal> cOSTOPROYECTADOENMNField;
        
        private System.Nullable<decimal> aCTUALIZADOCOSTOPROYECTADOENMNField;
        
        private System.Nullable<System.DateTime> fecha_ProcesoField;
        
        private System.Nullable<System.DateTime> fecha_ProcesarField;
        
        private System.Nullable<int> registrosActualizadosField;
        
        private System.Nullable<int> registrosdebieronActualizarseField;
        
        private string comentarioIniciadoField;
        
        private string comentarioFinalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Id_CifrasControl {
            get {
                return this.id_CifrasControlField;
            }
            set {
                this.id_CifrasControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Id_ListaHistorico {
            get {
                return this.id_ListaHistoricoField;
            }
            set {
                this.id_ListaHistoricoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Id_ListaCosto {
            get {
                return this.id_ListaCostoField;
            }
            set {
                this.id_ListaCostoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Id_ListaCostoDet {
            get {
                return this.id_ListaCostoDetField;
            }
            set {
                this.id_ListaCostoDetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Id_Prd {
            get {
                return this.id_PrdField;
            }
            set {
                this.id_PrdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Vigente {
            get {
                return this.vigenteField;
            }
            set {
                this.vigenteField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string NOMBREDEPROVEEDOR {
            get {
                return this.nOMBREDEPROVEEDORField;
            }
            set {
                this.nOMBREDEPROVEEDORField = value;
            }
        }
        
        /// <remarks/>
        public string NODEARTDEPROVEEDOR {
            get {
                return this.nODEARTDEPROVEEDORField;
            }
            set {
                this.nODEARTDEPROVEEDORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Fecha_Inicio {
            get {
                return this.fecha_InicioField;
            }
            set {
                this.fecha_InicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Fecha_Fin {
            get {
                return this.fecha_FinField;
            }
            set {
                this.fecha_FinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ORIGINALCOSTODECOMPRA {
            get {
                return this.oRIGINALCOSTODECOMPRAField;
            }
            set {
                this.oRIGINALCOSTODECOMPRAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> COSTODECOMPRA {
            get {
                return this.cOSTODECOMPRAField;
            }
            set {
                this.cOSTODECOMPRAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ACTUALIZADOCOSTODECOMPRA {
            get {
                return this.aCTUALIZADOCOSTODECOMPRAField;
            }
            set {
                this.aCTUALIZADOCOSTODECOMPRAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ORIGINALPRECIOMINIMODEVENTA {
            get {
                return this.oRIGINALPRECIOMINIMODEVENTAField;
            }
            set {
                this.oRIGINALPRECIOMINIMODEVENTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PRECIOMINIMODEVENTA {
            get {
                return this.pRECIOMINIMODEVENTAField;
            }
            set {
                this.pRECIOMINIMODEVENTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ACTUALIZADOPRECIOMINIMODEVENTA {
            get {
                return this.aCTUALIZADOPRECIOMINIMODEVENTAField;
            }
            set {
                this.aCTUALIZADOPRECIOMINIMODEVENTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ORIGINALCOSTODOLARES {
            get {
                return this.oRIGINALCOSTODOLARESField;
            }
            set {
                this.oRIGINALCOSTODOLARESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> COSTODOLARES {
            get {
                return this.cOSTODOLARESField;
            }
            set {
                this.cOSTODOLARESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ACTUALIZADOCOSTODOLARES {
            get {
                return this.aCTUALIZADOCOSTODOLARESField;
            }
            set {
                this.aCTUALIZADOCOSTODOLARESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ORIGINALPAAA {
            get {
                return this.oRIGINALPAAAField;
            }
            set {
                this.oRIGINALPAAAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PAAA {
            get {
                return this.pAAAField;
            }
            set {
                this.pAAAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ACTUALIZADOPAAA {
            get {
                return this.aCTUALIZADOPAAAField;
            }
            set {
                this.aCTUALIZADOPAAAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ORIGINALPLISTA {
            get {
                return this.oRIGINALPLISTAField;
            }
            set {
                this.oRIGINALPLISTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PLISTA {
            get {
                return this.pLISTAField;
            }
            set {
                this.pLISTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ACTUALIZADOPLISTA {
            get {
                return this.aCTUALIZADOPLISTAField;
            }
            set {
                this.aCTUALIZADOPLISTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ORIGINALPrecioBase {
            get {
                return this.oRIGINALPrecioBaseField;
            }
            set {
                this.oRIGINALPrecioBaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Preciobase {
            get {
                return this.preciobaseField;
            }
            set {
                this.preciobaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ACTUALIZADOPrecioBase {
            get {
                return this.aCTUALIZADOPrecioBaseField;
            }
            set {
                this.aCTUALIZADOPrecioBaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ORIGINALPAAAANTERIOR {
            get {
                return this.oRIGINALPAAAANTERIORField;
            }
            set {
                this.oRIGINALPAAAANTERIORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PAAAANTERIOR {
            get {
                return this.pAAAANTERIORField;
            }
            set {
                this.pAAAANTERIORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ACTUALIZADOPAAAANTERIOR {
            get {
                return this.aCTUALIZADOPAAAANTERIORField;
            }
            set {
                this.aCTUALIZADOPAAAANTERIORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ORIGINALPLISTAANTERIOR {
            get {
                return this.oRIGINALPLISTAANTERIORField;
            }
            set {
                this.oRIGINALPLISTAANTERIORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PLISTAANTERIOR {
            get {
                return this.pLISTAANTERIORField;
            }
            set {
                this.pLISTAANTERIORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ACTUALIZADOPLISTAANTERIOR {
            get {
                return this.aCTUALIZADOPLISTAANTERIORField;
            }
            set {
                this.aCTUALIZADOPLISTAANTERIORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ORIGINALCOSTOestandard {
            get {
                return this.oRIGINALCOSTOestandardField;
            }
            set {
                this.oRIGINALCOSTOestandardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> costoestandard {
            get {
                return this.costoestandardField;
            }
            set {
                this.costoestandardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ACTUALIZADOCOSTOestandard {
            get {
                return this.aCTUALIZADOCOSTOestandardField;
            }
            set {
                this.aCTUALIZADOCOSTOestandardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ORIGINALCOSTODECOMPRA_COMPRAS {
            get {
                return this.oRIGINALCOSTODECOMPRA_COMPRASField;
            }
            set {
                this.oRIGINALCOSTODECOMPRA_COMPRASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> COSTODECOMPRA_COMPRAS {
            get {
                return this.cOSTODECOMPRA_COMPRASField;
            }
            set {
                this.cOSTODECOMPRA_COMPRASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ACTUALIZADOCOSTODECOMPRA_COMPRAS {
            get {
                return this.aCTUALIZADOCOSTODECOMPRA_COMPRASField;
            }
            set {
                this.aCTUALIZADOCOSTODECOMPRA_COMPRASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ORIGINALCOSTOPROYECTADOENMN {
            get {
                return this.oRIGINALCOSTOPROYECTADOENMNField;
            }
            set {
                this.oRIGINALCOSTOPROYECTADOENMNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> COSTOPROYECTADOENMN {
            get {
                return this.cOSTOPROYECTADOENMNField;
            }
            set {
                this.cOSTOPROYECTADOENMNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ACTUALIZADOCOSTOPROYECTADOENMN {
            get {
                return this.aCTUALIZADOCOSTOPROYECTADOENMNField;
            }
            set {
                this.aCTUALIZADOCOSTOPROYECTADOENMNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Fecha_Proceso {
            get {
                return this.fecha_ProcesoField;
            }
            set {
                this.fecha_ProcesoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Fecha_Procesar {
            get {
                return this.fecha_ProcesarField;
            }
            set {
                this.fecha_ProcesarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RegistrosActualizados {
            get {
                return this.registrosActualizadosField;
            }
            set {
                this.registrosActualizadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RegistrosdebieronActualizarse {
            get {
                return this.registrosdebieronActualizarseField;
            }
            set {
                this.registrosdebieronActualizarseField = value;
            }
        }
        
        /// <remarks/>
        public string ComentarioIniciado {
            get {
                return this.comentarioIniciadoField;
            }
            set {
                this.comentarioIniciadoField = value;
            }
        }
        
        /// <remarks/>
        public string ComentarioFinal {
            get {
                return this.comentarioFinalField;
            }
            set {
                this.comentarioFinalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CatalogoListaPrecios {
        
        private System.Nullable<long> id_SubCatalogoField;
        
        private string descripcion_SubCatalogoField;
        
        private int seleccionadoField;
        
        private int seleccionadoSIANCENTRALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Id_SubCatalogo {
            get {
                return this.id_SubCatalogoField;
            }
            set {
                this.id_SubCatalogoField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion_SubCatalogo {
            get {
                return this.descripcion_SubCatalogoField;
            }
            set {
                this.descripcion_SubCatalogoField = value;
            }
        }
        
        /// <remarks/>
        public int Seleccionado {
            get {
                return this.seleccionadoField;
            }
            set {
                this.seleccionadoField = value;
            }
        }
        
        /// <remarks/>
        public int SeleccionadoSIANCENTRAL {
            get {
                return this.seleccionadoSIANCENTRALField;
            }
            set {
                this.seleccionadoSIANCENTRALField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetPriceListCompletedEventHandler(object sender, GetPriceListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPriceListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPriceListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaPrecios[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaPrecios[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetListaActualizadaCompletedEventHandler(object sender, GetListaActualizadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListaActualizadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListaActualizadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaPrecios[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaPrecios[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetAplicacionCompletedEventHandler(object sender, GetAplicacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAplicacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAplicacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CatalogoListaPrecios[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CatalogoListaPrecios[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetSubFamiliasCompletedEventHandler(object sender, GetSubFamiliasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSubFamiliasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSubFamiliasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CatalogoListaPrecios[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CatalogoListaPrecios[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetTipoProductoCompletedEventHandler(object sender, GetTipoProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTipoProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTipoProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CatalogoListaPrecios[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CatalogoListaPrecios[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetProveedorCompletedEventHandler(object sender, GetProveedorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProveedorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProveedorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CatalogoListaPrecios[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CatalogoListaPrecios[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetCampoListaCompletedEventHandler(object sender, GetCampoListaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCampoListaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCampoListaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CatalogoListaPrecios[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CatalogoListaPrecios[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetConfiguraListasCompletedEventHandler(object sender, GetConfiguraListasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConfiguraListasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConfiguraListasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CatalogoListaPrecios[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CatalogoListaPrecios[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PutHabilitarListaCompletedEventHandler(object sender, PutHabilitarListaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PutHabilitarListaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PutHabilitarListaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetPrecioPorAplicarCompletedEventHandler(object sender, GetPrecioPorAplicarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPrecioPorAplicarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPrecioPorAplicarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaPrecios[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaPrecios[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetPrecioIncidenciasCompletedEventHandler(object sender, GetPrecioIncidenciasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPrecioIncidenciasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPrecioIncidenciasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaPreciosIncidencias[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaPreciosIncidencias[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetPrecioLogEventosCompletedEventHandler(object sender, GetPrecioLogEventosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPrecioLogEventosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPrecioLogEventosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaPreciosIncidencias[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaPreciosIncidencias[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetFechaUltModCompletedEventHandler(object sender, GetFechaUltModCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFechaUltModCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFechaUltModCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetKeyCompletedEventHandler(object sender, GetKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591